# Change these first
owner: rifzkiadiyaksa # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: 🔵 Rifzki Adiyaksa
    url: https://rifzki.my.id
    icon: https://m.rifzki.my.id/assets/img/icon/72x72.png
  - name: 🔵 Blog Rifzki Adiyaksa
    url: https://rifzkia.blogspot.com
    icon: https://m.rifzki.my.id/assets/img/icon/72x72.png
  - name: 🔵 Games Rifzki Adiyaksa
    url: https://google.com
    icon: https://m.rifzki.my.id/assets/img/icon/72x72.png
  - name: 🔵 Music Rifzki Adiyaksa
    url: https://google.com
    icon: https://m.rifzki.my.id/assets/img/icon/72x72.png
  - name: Canada Server
    check: "tcp-ping"
    url: 1.1.1.1
    port: 53
  - name: Jakarta Server
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53
  - name: Singapore Server
    check: "tcp-ping"
    url: 1.1.1.1
    port: 53
  - name: Osaka Server
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53
  - name: Kuala Lumpur Server
    check: "tcp-ping"
    url: 1.1.1.1
    port: 53
  - name: Karawang Server
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53
  - name: Mumbai Server
    check: "tcp-ping"
    url: 1.1.1.1
    port: 53
  - name: Hongkong Server
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53
  - name: Seoul Server
    check: "tcp-ping"
    url: 1.1.1.1
    port: 53
  - name: CDN Asia Server
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53
  - name: CDN US Server
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53
  - name: CDN EU Server
    check: "tcp-ping"
    url: 1.1.1.1
    port: 53

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.rifzki.my.id
  # baseUrl: /your-repo-name
  favicon: https://m.rifzki.my.id/assets/img/icon/72x72.png
  logoUrl: https://m.rifzki.my.id/assets/img/icon/72x72.png
  name: Status Server
  introTitle: "**Status Server** check the server status and Rifzki Adiyaksa site."
  navbar:
    - title: Status
      href: /
    - title: Homepage
      href: https://rifzki.my.id

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
